/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperAdminsRouteImport } from './routes/super.admins'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppReferRouteImport } from './routes/app.refer'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminKitchenRouteImport } from './routes/admin.kitchen'
import { Route as AdminGrowthRouteImport } from './routes/admin.growth'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppSupportIndexRouteImport } from './routes/app.support.index'
import { Route as RiderDIdRouteImport } from './routes/rider.d.$id'
import { Route as AppTrackIdRouteImport } from './routes/app.track.$id'
import { Route as AppSupportIdRouteImport } from './routes/app.support.$id'
import { Route as ApiPublicHooksRetentionScanRouteImport } from './routes/api/public/hooks/retention-scan'
import { Route as ApiPublicHooksLockOrdersRouteImport } from './routes/api/public/hooks/lock-orders'
import { Route as ApiPublicHooksDispatchNotificationsRouteImport } from './routes/api/public/hooks/dispatch-notifications'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAdminsRoute = SuperAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppReferRoute = AppReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.finance.lazy').then((d) => d.Route))
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.analytics.lazy').then((d) => d.Route),
)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const RiderDIdRoute = RiderDIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => RiderRoute,
} as any)
const AppTrackIdRoute = AppTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIdRoute = AppSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksRetentionScanRoute =
  ApiPublicHooksRetentionScanRouteImport.update({
    id: '/api/public/hooks/retention-scan',
    path: '/api/public/hooks/retention-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLockOrdersRoute =
  ApiPublicHooksLockOrdersRouteImport.update({
    id: '/api/public/hooks/lock-orders',
    path: '/api/public/hooks/lock-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchNotificationsRoute =
  ApiPublicHooksDispatchNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-notifications',
    path: '/api/public/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/rider': typeof RiderRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/cart': typeof AppCartRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/super/': typeof SuperIndexRoute
  '/app/support/$id': typeof AppSupportIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/rider/d/$id': typeof RiderDIdRoute
  '/app/support/': typeof AppSupportIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/lock-orders': typeof ApiPublicHooksLockOrdersRoute
  '/api/public/hooks/retention-scan': typeof ApiPublicHooksRetentionScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/cart': typeof AppCartRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/rider': typeof RiderIndexRoute
  '/super': typeof SuperIndexRoute
  '/app/support/$id': typeof AppSupportIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/rider/d/$id': typeof RiderDIdRoute
  '/app/support': typeof AppSupportIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/lock-orders': typeof ApiPublicHooksLockOrdersRoute
  '/api/public/hooks/retention-scan': typeof ApiPublicHooksRetentionScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/rider': typeof RiderRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/app/cart': typeof AppCartRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/settings': typeof SuperSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/super/': typeof SuperIndexRoute
  '/app/support/$id': typeof AppSupportIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/rider/d/$id': typeof RiderDIdRoute
  '/app/support/': typeof AppSupportIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/lock-orders': typeof ApiPublicHooksLockOrdersRoute
  '/api/public/hooks/retention-scan': typeof ApiPublicHooksRetentionScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/rider'
    | '/super'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/growth'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/team'
    | '/admin/transactions'
    | '/app/cart'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/refer'
    | '/app/sessions'
    | '/app/subscriptions'
    | '/app/wallet'
    | '/super/admins'
    | '/super/settings'
    | '/admin/'
    | '/app/'
    | '/rider/'
    | '/super/'
    | '/app/support/$id'
    | '/app/track/$id'
    | '/rider/d/$id'
    | '/app/support/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/lock-orders'
    | '/api/public/hooks/retention-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/growth'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/team'
    | '/admin/transactions'
    | '/app/cart'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/refer'
    | '/app/sessions'
    | '/app/subscriptions'
    | '/app/wallet'
    | '/super/admins'
    | '/super/settings'
    | '/admin'
    | '/app'
    | '/rider'
    | '/super'
    | '/app/support/$id'
    | '/app/track/$id'
    | '/rider/d/$id'
    | '/app/support'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/lock-orders'
    | '/api/public/hooks/retention-scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/rider'
    | '/super'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/growth'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/team'
    | '/admin/transactions'
    | '/app/cart'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/refer'
    | '/app/sessions'
    | '/app/subscriptions'
    | '/app/wallet'
    | '/super/admins'
    | '/super/settings'
    | '/admin/'
    | '/app/'
    | '/rider/'
    | '/super/'
    | '/app/support/$id'
    | '/app/track/$id'
    | '/rider/d/$id'
    | '/app/support/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/lock-orders'
    | '/api/public/hooks/retention-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RiderRoute: typeof RiderRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
  ApiPublicHooksDispatchNotificationsRoute: typeof ApiPublicHooksDispatchNotificationsRoute
  ApiPublicHooksLockOrdersRoute: typeof ApiPublicHooksLockOrdersRoute
  ApiPublicHooksRetentionScanRoute: typeof ApiPublicHooksRetentionScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/admins': {
      id: '/super/admins'
      path: '/admins'
      fullPath: '/super/admins'
      preLoaderRoute: typeof SuperAdminsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/refer': {
      id: '/app/refer'
      path: '/refer'
      fullPath: '/app/refer'
      preLoaderRoute: typeof AppReferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/support/': {
      id: '/app/support/'
      path: '/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/rider/d/$id': {
      id: '/rider/d/$id'
      path: '/d/$id'
      fullPath: '/rider/d/$id'
      preLoaderRoute: typeof RiderDIdRouteImport
      parentRoute: typeof RiderRoute
    }
    '/app/track/$id': {
      id: '/app/track/$id'
      path: '/track/$id'
      fullPath: '/app/track/$id'
      preLoaderRoute: typeof AppTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/$id': {
      id: '/app/support/$id'
      path: '/support/$id'
      fullPath: '/app/support/$id'
      preLoaderRoute: typeof AppSupportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/retention-scan': {
      id: '/api/public/hooks/retention-scan'
      path: '/api/public/hooks/retention-scan'
      fullPath: '/api/public/hooks/retention-scan'
      preLoaderRoute: typeof ApiPublicHooksRetentionScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lock-orders': {
      id: '/api/public/hooks/lock-orders'
      path: '/api/public/hooks/lock-orders'
      fullPath: '/api/public/hooks/lock-orders'
      preLoaderRoute: typeof ApiPublicHooksLockOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-notifications': {
      id: '/api/public/hooks/dispatch-notifications'
      path: '/api/public/hooks/dispatch-notifications'
      fullPath: '/api/public/hooks/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCartRoute: typeof AppCartRoute
  AppMenuRoute: typeof AppMenuRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferRoute: typeof AppReferRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSupportIdRoute: typeof AppSupportIdRoute
  AppTrackIdRoute: typeof AppTrackIdRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartRoute: AppCartRoute,
  AppMenuRoute: AppMenuRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferRoute: AppReferRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppSupportIdRoute: AppSupportIdRoute,
  AppTrackIdRoute: AppTrackIdRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RiderRouteChildren {
  RiderIndexRoute: typeof RiderIndexRoute
  RiderDIdRoute: typeof RiderDIdRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderIndexRoute: RiderIndexRoute,
  RiderDIdRoute: RiderDIdRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface SuperRouteChildren {
  SuperAdminsRoute: typeof SuperAdminsRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAdminsRoute: SuperAdminsRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RiderRoute: RiderRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
  ApiPublicHooksDispatchNotificationsRoute:
    ApiPublicHooksDispatchNotificationsRoute,
  ApiPublicHooksLockOrdersRoute: ApiPublicHooksLockOrdersRoute,
  ApiPublicHooksRetentionScanRoute: ApiPublicHooksRetentionScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
